=== rlaboulaye/transformer/schema/task_schema.json
{
	"$schema": "http://json-schema.org/draft-04/schema",
	"definitions": {
		"task_type": {
			"type": "string",
			"enum": [
				"LanguageModeling",
				"DocumentClassification",
				"DocumentSimilarity",
				"MultipleChoice",
				"QuestionAnswering"
			]
		},
		"file_path": {
			"type": "string"
		},
		"index": {
			"type": "integer"
		},
		"indices": {
			"type": "array",
			"minItems": 1,
			"items": {
				"$ref": "#/definitions/index"
			}
		},
		"document": {
			"description": "The column_indices point to text columns that will be concatenated into a single document.",
			"type": "object",
			"properties": {
				"column_indices": {
					"$ref": "#/definitions/indices"
				}
			}
		},
		"document_list": {
			"description": "The documents to be used in the NLP task. The first document should be the principal document for each task. For MultipleChoice and QuestionAnswering, this will be the reference paragraph. For DocumentSimilarity, it can be either document.",
			"type": "array",
			"minItems": 1,
			"items": {
				"$ref": "#/definitions/document"
			}
		},
		"target": {
			"description": "This object points to the column index for the target. It should be used for all supervised tasks.",
			"type": "object",
			"properties": {
				"column_index": {
					"$ref": "#/definitions/index"
				}
			}
		}
	},
	"properties": {
		"task_type": {
			"$ref": "#/definitions/task_type"
		},
		"train_file_path": {
			"$ref": "#/definitions/file_path"
		},
		"test_file_path": {
			"$ref": "#/definitions/file_path"
		},
		"document_list": {
			"$ref": "#/definitions/document_list"
		},
		"target": {
			"$ref": "#/definitions/target"
		}
	},
	"required": [
		"task_type",
		"train_file_path",
		"document_list"
	]
}

=== rlaboulaye/transformer/schema/apple_task_schema.json
{
	"$schema": "task_schema.json",
	"task_type": "DocumentClassification",
	"train_file_path": "/users/data/d3m/datasets/training_datasets/LL1/LL1_apple_sentiment_analysis/LL1_apple_sentiment_analysis_dataset/tables/learningData.csv",
	"document_list"	: [
		{
			"column_indices": [
				1
			]
		}
	],
	"target": {
		"column_index": 2
	}
}

=== rlaboulaye/transformer/schema/cloze_task.json
{
	"$schema": "task_schema.json",
	"task_type": "MultipleChoice",
	"train_file_path": "/users/grads/r/rdalbest/Documents/cloze/cloze_test_val__spring2016 - cloze_test_ALL_val.csv",
	"test_file_path": "/users/grads/r/rdalbest/Documents/cloze/cloze_test_test__spring2016 - cloze_test_ALL_test.csv",
	"document_list"	: [
		{
			"column_indices": [
				1,
				2,
				3,
				4
			]
		},
		{
			"column_indices": [
				5
			]
		},
		{
			"column_indices": [
				6
			]
		}
	],
	"target": {
		"column_index": 7
	}
}

=== rlaboulaye/transformer/schema/self_drive_schema.json
{
	"$schema": "task_schema.json",
	"task_type": "DocumentClassification",
	"train_file_path": "/users/data/d3m/datasets/training_datasets/LL1/LL1_sentiment_self_drive/LL1_sentiment_self_drive_dataset/tables/learningData.csv",
	"document_list"	: [
		{
			"column_indices": [
				1
			]
		}
	],
	"target": {
		"column_index": 2
	}
}
